"""
File containing all string variables and tags used across the plugin.
"""

SPARQL_PYPADS_ONTO = "SPARQL_PYPADS_ONTO"

SPARQL_GRAPH = "SPARQL_GRAPH"
SPARQL_QUERY_ENDPOINT = "SPARQL_QUERY_ENDPOINT"
SPARQL_UPDATE_ENDPOINT = "SPARQL_UPDATE_ENDPOINT"
SPARQL_AUTH_NAME = "SPARQL_AUTH_NAME"
SPARQL_AUTH_PASSWORD = "SPARQL_AUTH_PASSWORD"
